### ISSUE TITLE
Map: how we deal with dataset?

### ISSUE THREAD

**Issue by uf0** [C2DH/post-175#46]
We will have `.csv` files as document to be used in the Map view

**Comment by danieleguido** [comment]
@uf0 are the csv file linked to a specific document? 
Otherwise we can just add a document *per dataset* with type `csv` and attachment `csv/file.csv`
What do you think?

**Comment by danieleguido** [comment]
@uf0 the csv is now a [separate document](https://luxptt.dhlab.lu/api/document/itu-stats/) its lsug being `itu-stats`.
Documents have been updated, I have added the support for document type `csv` in Document class, ref. https://github.com/C2DH/miller/commit/5fe0518224ccbc26075192800782bf04823beaa2
