### ISSUE TITLE
Boolean value not imported form spreadsheet

### ISSUE THREAD

**Issue by uf0** [C2DH/post-175#47]
![screen shot 2018-10-29 at 14 39 52](https://user-images.githubusercontent.com/1922342/47653326-906e8f00-db88-11e8-8531-fc97922b09a4.png)

**Comment by danieleguido** [comment]
Fixed in https://github.com/C2DH/miller/commit/648ea6d48034f8c3921b21f362a5cc5d47c81d02

Documents have been already updated.
